const cameras = [
  {
    name: 'Nikon - Z 8 8K Video Mirrorless Camera (Body Only) - Black',
    description:'The ultimate hybrid camera. Powerful video and still photography capabilities. Video features include 12-bit 8K/60p and 4K/120p RAW plus 10-bit ProRes 422 HQ internal video recording. Photography features include a 45.7MP stacked CMOS sensor, a silent, vibration-free electronic shutter, 120 fps burst shooting and a blackout-free viewfinder. Fast, accurate AF with subject detection powered by deep learning. Professional build and operation. Smart connectivity. All in a brilliant compact, lightweight modular design.',
    image: '/assets/images/Nikon-Z-Mirrorless.jpeg',
    price: 3699.99,
    quantity: 100,
    category: 'Cameras',
  },
  {
    name: 'Canon - EOS R6 Mark II Mirrorless Camera (Body Only) - Black',
    description:'Introducing a standard full-frame camera evolved with hybrid features for still and movie shooting. The EOS R6 Mark II enables various photographic expressions that transcend boundaries between recording personal life and professional production purposes, as well as between photo shooting and movie shooting. Achieve creativity in everyday life with the EOS R6 Mark II.',
    image: '/assets/images/Canon-EOS-MKII.jpeg',
    price: 1999.99,
    quantity: 100,
    category: 'Cameras',
  },
  {
    name:'Sony - Alpha a7 III Mirrorless Camera with FE 28-70 mm',
    description:'Capture stunning portraits and beautiful action shots with this Sony a7 III full-frame mirrorless camera with FE 28-70mm standard zoom lens. Optical SteadyShot image stabilization delivers blur-free, crisp images, while the seven-blade circular aperture delivers more natural-looking bokeh effects. With its dust- and moisture-resistant design, this camera is ideal for both indoor and outdoor photo shoots. ',
    image:'/assets/images/Sony-Alpha-a7.jpeg',
    price: 1499.99,
    quantity: 100,
    category:'Cameras',
  },
  {
    name:'Fujifilm - X-T30 II Mirrorless Camera with XC 15-45mm Lens',
    description:'Cleverly weaving proven technology with a vintage aesthetic, X-T30 II has much to offer stills photographers and videographers of all levels. The 26.1MP back-illuminated X-Trans sensor and X-Processor 4 imaging engine combine to deliver exceptional performance, with autofocusing down to -7EV in just 0.02 secs – and detail-packed results full of vibrant color. Pick up and start creating in seconds by flicking over to the Advanced SR Auto mode, or take more control over your output. ',
    image:'/assets/images/Fujifilm-X-T30.jpeg',
    price: 999.99,
    quantity: 100,
    category:'Cameras',
  },
  {
    name:'Nikon - Z fc 4K Video Mirrorless Camera w/ NIKKOR Z DX 16-50mm f/3.5-6.3 VR - Black/Silver',
    description:'The Z fc mirrorless camera features a classic, tactile design fused with modern Z series technology. Equipped with a flip out vlogger screen, this DX-format 4K UHD compact camera delivers big image quality for photos and videos. ',
    image:'/assets/images/Nikon-Z-fc.jpeg',
    price: 1099.99,
    quantity:100,
    category:'Cameras',
  },
  {
    name:'Canon - EOS Rebel T7 DSLR Video Camera with 18-55mm Lens - Black',
    description: 'Take professional-looking photos with this Canon DSLR camera bundle. The 24.1-megapixel CMOS sensor captures the smallest details, even in low light, and the optical image stabilizer technology ensures handheld shots are sharp. The 18-55mm lens included in this Canon DSLR camera bundle is suitable for taking wide-angle pictures or zooming in for portraits. ',
    image:'/assets/images/Canon-EOS-Rebel.jpeg',
    price: 479.00,
    quantity:100,
    category:'Cameras',
  },
  {
    name:'Nikon - D7500 DSLR 4K Video Camera with AF-S DX NIKKOR 18-140mm',
    description: 'Take a wide range of photos with this Nikon D7500 digital camera. It includes an 18-140mm VR lens so you can enjoy shooting wide-angle to portrait, to telephoto, and a large 20.9-megapixel sensor combines with EXPEED 5 processing to deliver absolute precision. A rugged body ensures this Nikon D7500 handles everyday use. ',
    image:'/assets/images/Nikon-D7500.jpeg',
    price: 1179.99,
    quantity:100,
    category:'Cameras',
  },
  {
    name:'Canon - EOS 90D DSLR Camera with EF-S 18-135mm Lens - Black',
    description:'Immortalize precious memories with this Canon EOS 90D and EF-S 18-135mm lens camera kit. Intuitive controls make it easy to adjust settings and optimize image quality, and the included lens lets you zoom in on subjects. A 32.5MP CMOS sensor lets this Canon EOS 90D and EF-S18-135mm lens camera kit take lifelike still images and record videos in up to 4K resolution.',
    image:'/assets/images/Canon-EOS-90D.jpeg',
    price:1599.99,
    quantity:100,
    category:'Cameras',
  },
  {
    name:'Canon - EOS 5D Mark IV DSLR Camera (Body Only) - Black',
    description:'Step up your photography with the Canon EOS 5D Mark IV body. It has a 30.4-megapixel full-frame CMOS sensor and a 100-32,000 ISO range that lets you take large photos that are sharp and bright. The Canon EOS 5D Mark IV body is ideal for shooting action photos with speeds of up to seven frames per second.',
    image:'/assets/images/Canon-EOS-5D.jpeg',
    price:2099.99,
    quantity:100,
    category:'Cameras',
  },
  {
    name:'Canon - EOS 5D Mark IV DSLR Camera with 24-105mm f/4L Lens',
    description:'Shoot beautiful images in almost any lighting with this Canon EOS 5D camera. Its 30.4-megapixel full-frame sensor captures vivid detail for beautiful travel and event montages. Its 4K motion JPEG video capability helps you preserve precious moments, while its increased responsiveness provides smooth recording. The built-in GPS on this Canon EOS 5D camera helps you geotag photos.',
    image:'/assets/images/Canon-EOS-5D-MKIV.jpeg',
    price:3199.99,
    quantity:100,
    category:'Cameras',
  },
  {
    name:'Sony - ZV-1F Vlog Camera for Content Creators and Vloggers - Black',
    description:'Sony ZV-1F Vlog camera for Content Creators and Vloggers, large 1-inch sensor with wide angle 20mm1 lens and packed with easy-to-use features, specifically designed for vloggers and online video creators. ',
    image:'/assets/images/Sony-ZV-Black.jpeg',
    price:479.99,
    quantity:100,
    category:'Cameras',
  },
  {
    name:'Sony - ZV-1F Vlog Camera for Content Creators and Vloggers - White',
    description:'Sony ZV-1F Vlog camera for Content Creators and Vloggers, large 1-inch sensor with wide angle 20mm1 lens and packed with easy-to-use features, specifically designed for vloggers and online video creators. ',
    image:'/assets/images/Sony-ZV-White.jpeg',
    price:479.99,
    quantity:100,
    category:'Cameras',
  }
];

module.exports = cameras;
