const cellPhones = [
  {
    name: 'Apple - iPhone 15 256GB - Blue (AT&T)',
    description:'This phone brings you Dynamic Island, a 48MP Main camera, and USB-C—all in a durable color-infused glass and aluminum design.',
    image: '/assets/images/iphone15.jpg',
    price: 1099.97,
    quantity: 50,
    category: 'Cell Phones',
  },
  {
    name: 'Apple - iPhone 14 128GB (Unlocked) - Midnight',
    description:'With the most impressive dual-camera system on iPhone. Capture stunning photos in low light and bright light. Get peace of mind with groundbreaking safety features.',
    image: '/assets/images/iphone14.jpg',
    price: 679.94,
    quantity: 15,
    category: 'Cell Phones',
  },
  {
    name: 'Apple - iPhone 13 5G 128GB - Midnight',
    description:'The most advanced dual-camera system ever on iPhone. Lightning-fast A15 Bionic chip. A big leap in battery life. Durable design. Superfast 5G.¹ And a brighter Super Retina XDR display.',
    image: '/assets/images/iphone13.jpg',
    price: 598.94,
    quantity: 25,
    category: 'Cell Phones',
  },
  {
    name: 'Apple - iPhone SE (3rd Gen) 64GB - Black',
    description:'Lightning-fast A15 Bionic chip and fast 5G.1 Big-time battery life and a superstar camera. Plus, the toughest glass in a smartphone and a Home button with secure Touch ID.',
    image: '/assets/images/iphoneSE.jpg',
    price: 399.99,
    quantity: 10,
    category: 'Cell Phones',
  },
  {
    name: 'Samsung - Galaxy S24 128GB (Unlocked) - Amber Yellow',
    description:'Make every day epic with Galaxy AI on Galaxy S24. See a delicious looking dish on your social feed but don’t see a recipe? Simply Circle to Search with Google to find it in seconds. Then head to a sunny farmer’s market to pick up the ingredients and see your list clearly on the bright, adaptive display of Galaxy S24. Once the meal is ready, capture stunning close ups of your dish and dinner guests, no matter the lighting, with a high res camera and Nightography. And all the while, you can stay plugged into the moment, not the outlet, with a long lasting battery. Do more easily with Galaxy AI on Galaxy S24. Epic, just like that.',
    image: '/assets/images/galaxyS24.jpg',
    price: 999.99,
    quantity: 40,
    category: 'Cell Phones',
  },
  {
    name: 'Samsung - Galaxy Z Flip6 512GB (Unlocked) - Mint',
    description:'Unlock your creativity with the tiny but mighty Galaxy Z Flip6, the Galaxy AI powered pocket perfect foldable built for those who want to make a big statement. Easily find your best angle using FlexCam with Galaxy AI, which automatically zooms for the perfect hands free shot every time. Simplify life on the go with Galaxy AI on FlexWindow, where you can get quick reply text suggestions based on the context of your conversation. You can also use FlexWindow to check health tracking data and insights from a paired Galaxy Ring without opening your phone. Get your hands on Galaxy Z Flip6 the Galaxy AI foldable that’s a perfect mix of compact and powerful.',
    image: '/assets/images/galaxyFlip.jpg',
    price: 1219.99,
    quantity: 20,
    category: 'Cell Phones',
  },
  {
    name:'Samsung - Galaxy S23 256GB (Unlocked) - Phantom Black',
    description:'Meet the Samsung Galaxy S23, the phone that takes you out of the everyday and into the epic. Record in stunning detail with cinematic 8K Video @ 30fps – the highest recording resolution available on a smartphone. Enjoy your favorite content on a bright, beautiful 6.1” FHD+ Dynamic AMOLED display. Capture vivid detail with a triple lens camera and a 50MP resolution main lens with up to 30X digital zoom. Life doesn’t wait for the perfect lighting, but with Nightography, you are always ready to seize the moment even in low light and snap memories like a pro. See your content no matter the time of day on a display with a refresh rate up to 120Hz and Adaptive Vision Booster. Best of all experience all this on the nation’s largest and fastest nationwide 5G network1.',
    image: '/assets/images/galaxyS23.jpg',
    price: 599.99,
    quantity: 35,
    category: 'Cell Phones',
  },
  {
    name: 'Samsung - Galaxy S22 128GB (Unlocked) - Pink Gold',
    description:'This phone is redefining the epic standard both for what a smartphone can do with video and for what you can communicate, create, and experience with it. In other words, if you have got something to say, Galaxy S22 makes it possible to say anything you want with video, at any time-even in the darkness of night.',
    image: '/assets/images/galaxyS22.jpg',
    price: 429.99,
    quantity: 30,
    category: 'Cell Phones',
  },
  {
    name: 'Google - Pixel 9 128GB (Unlocked) - Obsidian',
    description: 'Meet Pixel 9 with Gemini. Engineered by Google, Pixel gets the best of Google’s AI first. So you can take amazing photos, make edits like magic, and get things done even easier. Pixel can protect against spam and other threats. It helps you in an emergency.10 And it’s built to last.',
    image: '/assets/images/pixel9.jpg',
    price: 899.99,
    quantity: 55,
    category: 'Cell Phones',
  },
  {
    name: 'Google - Pixel 8 256GB (Unlocked) - Obsidian',
    description:'The helpful phone engineered by Google, with an amazing camera, powerful security, and an all-day battery. With Google AI, you can do more, even faster – like fix photos, screen calls, and get answers and Pixel 8 has personal safety features for added peace of mind.',
    image: '/assets/images/pixel8.jpg',
    price: 759.99,
    quantity: 45,
    category: 'Cell Phones',
  },
  {
    name: 'Google - Pixel 7 256GB (Unlocked) - Lemongrass',
    description:'Powered by Google Tensor G2, it’s fast and secure, with amazing battery life and the advanced Pixel Camera. Take beautifully authentic, accurate photos with Real Tone and stunning video with Cinematic Blur. And with the certified Titan M2 security chip and a built-in VPN, Pixel helps protect your personal data.',
    image: '/assets/images/pixel7.jpg',
    price: 699.99,
    quantity: 35,
    category: 'Cell Phones',
  },
  {
    name: 'Google - Pixel 6 128GB (Unlocked) - Kinda Coral',
    description:'Meet Pixel 6. It’s completely reimagined, inside and out. Powered by Tensor, Google’s first-ever processor, it’s fast, smart, and secure. The all-day battery adapts to you.* The Pixel Camera captures a moment just how you experienced it. And the Personal Safety app and the new Titan M2TM chip help protect you, your stuff, and your privacy.',
    image: '/assets/images/pixel6.jpg',
    price: 209.99,
    quantity: 20,
    category: 'Cell Phones',
  },
];

module.exports = cellPhones;