const home = [
  {
    name: 'Airpods',
    description:'apple product',
    image: '/assets/images/PlayStation 5.jpeg',
    price: 180.99,
    quantity: 100,
    category: 'Home',
  },
  {
    name: 'Airpods',
    description:'apple product',
    image: '/assets/images/PlayStation 5.jpeg',
    price: 180.99,
    quantity: 100,
    category: 'Home',
  },
  {
    name: 'Airpods',
    description:'apple product',
    image: '/assets/images/PlayStation 5.jpeg',
    price: 180.99,
    quantity: 100,
    category: 'Home',
  },
  {
    name: 'Airpods',
    description:'apple product',
    image: '/assets/images/PlayStation 5.jpeg',
    price: 180.99,
    quantity: 100,
    category: 'Home',
  },
  {
    name: 'Gift Cards',
    description:'apple product',
    image: '/assets/images/PlayStation 5.jpeg',
    price: 500.00,
    quantity: 50,
    category: 'Home',
  },
  {
    name: 'Gift Cards',
    description:'apple product',
    image: '/assets/images/PlayStation 5.jpeg',
    price: 500.00,
    quantity: 50,
    category: 'Home',
  },
  {
    name: 'Gift Cards',
    description:'apple product',
    image: '/assets/images/PlayStation 5.jpeg',
    price: 500.00,
    quantity: 50,
    category: 'Home',
  },
  {
    name: 'Gift Cards',
    description:'apple product',
    image: '/assets/images/PlayStation 5.jpeg',
    price: 500.00,
    quantity: 50,
    category: 'Home',
  },
  {
    name: 'Infinity Stone',
    description:'weak ahh stones',
    image: '/assets/images/PlayStation 5.jpeg',
    price: 1000.00,
    quantity: 5,
    category: 'Home',
  },
  {
    name: 'Infinity Stone',
    description:'weak ahh stones',
    image: '/assets/images/PlayStation 5.jpeg',
    price: 1000.00,
    quantity: 5,
    category: 'Home',
  },
  {
    name: 'Infinity Stone',
    description:'weak ahh stones',
    image: '/assets/images/PlayStation 5.jpeg',
    price: 1000.00,
    quantity: 5,
    category: 'Home',
  },
  {
    name: 'Infinity Stone',
    description:'weak ahh stones',
    image: '/assets/images/PlayStation 5.jpeg',
    price: 1000.00,
    quantity: 5,
    category: 'Home',
  },
];

module.exports = home;