const home = [
  {
    name: 'Call of Duty: Black Ops 6 Standard Edition - PlayStation 5',
    description:'Developed by Treyarch and Raven, Call of Duty: Black Ops 6 is a spy action thriller set in the early 90s, a period of transition and upheaval in global politics, characterized by the end of the Cold War and the rise of the United States as a single superpower. With a mind-bending narrative, and unbound by the rules of engagement, this is signature Black Ops across a cinematic single-player Campaign, a best-in-class Multiplayer experience, and with the epic return of Round-Based Zombies.',
    image: '/assets/images/BO6.jpg',
    price: 69.99,
    quantity: 100,
    category: 'Home',
  },
  {
    name: 'Grand Theft Auto VI Standard Edition - PlayStation 5',
    description:'Includes Grand Theft Auto VI: Story Mode and Grand Theft Auto Online. Continue your journey on PS5 and transfer both GTAVI Story Mode progress and GTA Online characters and progression to PS5 with a one-time migration.',
    image: '/assets/images/GTA6.jpg',
    price: 79.99,
    quantity: 100,
    category: 'Home',
  },
  {
    name: 'Riot Games - Valorant $100 (Digital Delivery)',
    description:"Customize your VALORANT experience based on your personal style! Unlock Weapon Skins: When you ace the enemy team, make sure they know you're doing it in style. Weapon skins are designed to be cosmetic only and do not provide a positive or negative gameplay advantage. The perfect gift for anyone who plays VALORANT or trying it out for the first time.",
    image: '/assets/images/valorant-giftcard-$100.jpg',
    price: 100,
    quantity: 100,
    category: 'Home',
  },
  {
    name: 'Riot Games - Valorant $50 (Digital Delivery)',
    description:"Customize your VALORANT experience based on your personal style! Unlock Weapon Skins: When you ace the enemy team, make sure they know you're doing it in style. Weapon skins are designed to be cosmetic only and do not provide a positive or negative gameplay advantage. The perfect gift for anyone who plays VALORANT or trying it out for the first time.",
    image: '/assets/images/valorant-giftcard-$50.jpg',
    price: 50,
    quantity: 100,
    category: 'Home',
  },
  {
    name: 'Apple Watch SE 2nd Generation (GPS + Cellular) 40mm Starlight Aluminum Case with Starlight Sport Band - M/L - Starlight',
    description:'Essential features to help you stay connected, active, healthy, and safe. Perfect for kids and older adults using Family Setup. ',
    image: '/assets/images/Apple-Watch-Starlight.jpeg',
    price: 290.00,
    quantity: 100,
    category: 'Home',
  },
  {
    name: 'Lectric eBikes - XP Step-Thru 3.0 Foldable Long-Range eBike with 65 miles Max Operating Range & 28 mph Max Speed - Unisize - Black',
    description:'The Lectric XP 3.0 is your gateway to an elevated and powerful adventure! It takes our award-winning XP 2.0 design to the next level, providing our best ride to date. A quieter motor, increased torque, hydraulic brakes, longevity boosters, and added suspension are only a few of the many notable upgrades with this epic utility eBike design. Best of all, brand-new optimized gearing makes riding at higher speeds smoother than ever before! ',
    image: '/assets/images/Lectric-eBikes.jpeg',
    price: 1199.00,
    quantity: 100,
    category: 'Home',
  },
  {
    name: 'Walker Edison - Harbor 3-Piece Acacia Wood Patio Sectional - Dark Brown',
    description:'Create a cozy chat set or a chaise-like bench with this three-piece modular patio set that includes two corner chairs and one ottoman. The cushions are three-inches, have removable UV resistant cushion covers, and hook and loop fasteners to keep them securely in place. The naturally weather-resistant solid acacia wood frame should be treated with teak oil every 2-3 months to maintain its vibrant color and durability. ',
    image: '/assets/images/Walker-Edison.jpeg',
    price: 419.99,
    quantity: 100,
    category: 'Home',
  },
  {
    name: 'Hyperice - Hypervolt 2 Pro Premium Percussion Massage Device - Black',
    description:"Get the same powerful percussion massage therapy that the world's best athletes have—right in the palm of your hand. Now with more power, and variable speeds, the Hypervolt 2 Pro Premium helps you recover faster so you can get back to doing more of what you love.",
    image: '/assets/images/Hyperice-Massage-Device.jpeg',
    price: 329.00,
    quantity: 100,
    category: 'Home',
  },
  {
    name: 'TCL - 115" Class QM8 4K LED Smart Google TV',
    description:"TCL’s Flagship 115” QD-Mini LED TV combines stunning 4K HDR, Quantum Dot Mini-LED technology in a 360° metal bezel-less design for a true flagship TV experience. With the QLED PRO technology and the HDR ULTRA with Dolby Vision IQ, you can enjoy enhanced contrast, vivid colors, and fine details. TCL’s High Brightness ULTIMATE Direct LED Backlight produces up to 5,000 nits peak brightness for dazzling specular highlights, perfect for any viewing environment. QD-Mini LED, with over 20,000 zones, adapts to on-screen content for deep blacks without image blooming powered by TCL's AIPQ ULTRA Processor, an advanced processor optimizing each scene with machine learning for an unrivaled cinematic experience. ",
    image: '/assets/images/TCL-TV.jpeg',
    price: 19999.99,
    quantity: 100,
    category: 'Home',
  },
  {
    name: 'Roku - 43" Class Select Series 4K Smart RokuTV',
    description:'Roku Select Series 4K TVs are thoughtfully designed to upgrade your entertainment at an incredible value. Enjoy your streaming favorites in brilliant 4K HDR picture that’s optimized for your room lighting with automatic brightness. Catch every word with built-in sound features like auto speech clarity and night mode or enjoy private listening with headphones.',
    image: '/assets/images/Roku-TV.jpeg',
    price: 219.99,
    quantity: 100,
    category: 'Home',
  },
  {
    name: 'Insignia - 65" Class F30 LED 4K Smart Fire TV',
    description:'Take in every moment with breathtaking 4K Ultra HD on this 65-inch screen. It’s equipped with DTS Studio Sound to create realistic and immersive audio. Access live over-the-air channels and streaming—and control it all with your voice. Ask Alexa to launch apps, search for titles and more. Experience the affordable, yet high-performing Insignia NS-65F301NA23 65" Class F30 Series LED 4K UHD Smart Fire TV. ',
    image: '/assets/images/Insignia-TV.jpeg',
    price: 349.99,
    quantity: 100,
    category: 'Home',
  },
  {
    name: 'Samsung - 75” Class Crystal 4K Smart Tizen TV',
    description:'This essential TV features a range of contrast and color and smart capabilities. Enjoy your content with richer details, brighter images and clearer resolution with 4K Upscaling ',
    image: '/assets/images/Samsung-TV.jpeg',
    price: 569.99,
    quantity: 100,
    category: 'Home',
  },
];

module.exports = home;