const videoGames = [
  {
    name: 'PlayStation 5 Slim Console Digital Edition',
    description:"Vertical stand not included. The PS5 Digital Edition unleashes new gaming possibilities that you never anticipated. PS5 Digital Edition is an all-digital version of the PS5 console with no disc drive. Sign into your account for PlayStation Network and go to PlayStation Store to buy and download games. 2 *PS5 Digital Edition (CFI-2000 model group – slim) 2Account for PlayStation Network required. Full terms apply – playstation.com/PSNTerms..",
    image: '/assets/images/PlayStation 5.jpeg',
    price: 249.99,
    quantity: 100,
    category: 'Video Games',
  },
  {
    name: 'PlayStation 5 Slim Console',
    description:'Vertical stand not included. The PS5 console unleashes new gaming possibilities that you never anticipated. Experience lightning fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio2, and an all-new generation of incredible PlayStation games. *PS5 console (CFI-2000 model group – slim) 23D audio via built-in TV speakers or analog/USB stereo headphones. Set up and latest system software update required..',
    image: '/assets/images/PlayStation5-Slim.jpeg',
    price: 469.98,
    quantity: 100,
    category: 'Video Games',
  },
  {
    name:'PlayStation 5 Slim Console Digital Edition – NBA 2K25 Bundle',
    description:'PlayStation 5 Digital Edition – NBA 2K25 Bundle includes: PlayStation 5 Digital Edition, 1TB SSD, Disc Drive4, DualSense wireless controller, 2 Horizontal stand feet, HDMI cable, AC power cord, USB cable, Printed materials, ASTRO’s PLAYROOM (Pre-installed game. PS5 console may need to be updated to the latest system software version. Internet connection required.), NBA 2K25 Standard Edition voucher1 PlayStation 5 Digital Edition (model group – slim) The PS5 Digital Edition unleashes new gaming possibilities that you never anticipated. PS5 Digital Edition is an all-digital version of the PS5 console with no disc drive.',
    image:'/assets/images/PlayStation5-2k.jpeg',
    price:499.99,
    quantity:100,
    category:'Video Games',
  },
  {
    name:'Nintendo - Switch with Blue and Red Joy‑Con',
    description:'Play at home or on the go with one system. The Nintendo Switch system is designed to go wherever you do, instantly transforming from a home console you play on TV to a portable system you can play anywhere. So you get more time to play the games you love, however you like. Enjoy three modes in one system. TV mode: Connect your system to the TV using the included dock to enjoy a traditional gaming experience in HD. Handheld mode: Bring your games on your next travel adventure, or simply carve out some “me” time in the coziest seat in the house. ',
    image:'/assets/images/Nintendo-switch.jpeg',
    price:299.99,
    quantity:100,
    category:'Video Games',
  },
  {
    name:'Nacon - Revolution 5 Pro Wireless Controller for PS5, PS4 and PC - Black',
    description:'Boost your skills with the controller innovations from Nacon. Officially licensed for PlayStation, the Revolution 5 Pro delivers unmatched performance and reliability in a wireless game controller for PS5, PS4 and PC. Revolutionary features include magnetic Hall effect joysticks, adjustable trigger blockers, swappable D-pad designs, and Bluetooth audio. ',
    image:'/assets/images/Nacon.jpeg',
    price:199.99,
    quantity:100,
    category:'Video Games',
  },
  {
    name:'Logitech - G923 Racing Wheel and Pedals for PS5, PS4 and PC - Black',
    description:'Logitech G923 for PlayStation 5, PlayStation 4 and PC is a high-performance racing wheel that revolutionizes the racing experience. Re-engineered to support a next-generation feedback system, G923 features TRUEFORCE high-definition force feedback that dials into game engines to deliver higher-fidelity realism. Feel the pistons pumping, the gravel crunching, and every shift, drift, and hairpin turn like never before. True racing comes from within. ',
    image:'/assets/images/Logitech-Racing-Wheel.jpeg',
    price:299.99,
    quantity:100,
    category:'Video Games',
  },
  {
    name:'PowerA - Wireless Controller for Nintendo Switch - Mario Joy',
    description:'Officially licensed by Nintendo, the PowerA Wireless Controller for Nintendo Switch looks amazing and plays even better. Each controller features gorgeous designs and is engineered to ensure optimal in-game performance and reliability. Program two mappable Advanced Gaming Buttons on-the-fly and enjoy hours of gaming with super-comfortable ergonomics.',
    image:'/assets/images/Mario-Controller.jpeg',
    price:34.99,
    quantity:100,
    category:'Video Games',
  },
  {
    name:'Nintendo - Joy-Con (L/R) Wireless Controllers - Pastel Pink/Pastel Yellow',
    description:'Nintendo - Joy-Con (L/R) Wireless Controllers - Pastel Pink/Pastel Yellow',
    image:'/assets/images/Nintendo-Joycon.jpeg',
    price:79.99,
    quantity:100,
    category:'Video Games',
  },
  {
    name:'Until Dawn – PS5 - PlayStation 5',
    description:'When eight friends return to the isolated lodge where two of their group vanished a year prior, fear tightens its icy grip, and their mountain retreat descends into a nightmare with no escape. Face your fears and determine who survives Until Dawn in this seminal horror classic, rebuilt and enhanced for PS5 consoles.',
    image:'/assets/images/Until-Dawn.jpeg',
    price:59.99,
    quantity:100,
    category:'Video Games',
  },
  {
    name:'Elden Ring Shadow of the Erdtree Edition - PlayStation 5',
    description:'ELDEN RING, winner of hundreds of accolades including The Game Awards’ “Game of the Year” and Golden Joystick Awards’ “Ultimate Game of the Year,” is bringing a new adventure to the Tarnished in the Lands Between. ELDEN RING Shadow of the Erdtree DLC is From Software’s largest expansion to date, where players must unravel the hidden mystery of the world from the acclaimed fantasy action RPG.',
    image:'/assets/images/Elden-Ring.jpeg',
    price:79.99,
    quantity:100,
    category:'Video Games',
  },
  {
    name:'Minecraft Starter Collection - PlayStation 4, PlayStation 5',
    description:'Minecraft is a game about placing blocks and going on adventures. Build anything you can imagine with unlimited resources in Creative mode, or go on grand expeditions in Survival, journeying across mysterious lands and into the depths of your own infinite worlds. Will you hide from monsters or craft tools, armor, and weapons to fight back? No need to go alone. Share the adventure with friends in split-screen multiplayer and online.¹',
    image:'/assets/images/Minecraft.jpeg',
    price:29.99,
    quantity:100,
    category:'Video Games',
  },
  {
    name:'ARK: Survival Ascended - PlayStation 5',
    description:'Respawn into a new dinosaur survival experience beyond your wildest dreams… as ARK is reimagined from the ground-up into the next-generation of videogame technology with Unreal Engine 5! You awake on a mysterious island, your senses overwhelmed by the blinding sunlight and brilliant colors bouncing off every surface around you, the azure waters of a verdant Island lapping at your bare feet. A deep roar echoes from the misty jungle, jolting you into action, and you stand up – not afraid, but intrigued. Are you ready to form a tribe, tame and breed hundreds of species of dinosaurs and other primeval creatures, explore, craft, build, and fight your way to the top of the food-chain? Your new world awaits… step through the looking-glass and join it! ',
    image:'/assets/images/Ark.jpeg',
    price:44.99,
    quantity:100,
    category:'Video Games',
  },
];

module.exports = videoGames;